In [1]:
from tensorflow import keras 
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from ultralytics import YOLO
import cv2
import pickle
from pathlib import Path
import matplotlib.pyplot as plt

import numpy as np
import os

2024-12-04 23:25:04.491262: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
file_path = 'best_model.keras'
print(f"File exists: {os.path.exists(file_path)}")

File exists: True


In [3]:
model = keras.models.load_model('best_model.keras')

In [4]:
X_test = np.load("./flower_species_classification/data_test.npy").T/ 255.0
t_test = np.load("./flower_species_classification/labels_test.npy")

X_test.shape

(415, 270000)

In [6]:
X_test = X_test.reshape((X_test.shape[0], 300, 300, 3))
t_pred = model.predict(X_test)

t_pred_list = []
for i in t_pred:
    t_pred_list.append(np.argmax(i))
t_pred = np.array(t_pred_list)
accuracy = accuracy_score(y_pred=t_pred, y_true=t_test)
print(f"Accuracy is {accuracy}")

13/13 ━━━━━━━━━━━━━━━━━━━━ 136s 11s/step
Accuracy is 0.8506024096385543


In [ ]:
confusionMatrix = confusion_matrix(y_pred= t_pred, y_true = t_test)
print(confusionMatrix)

In [5]:
classififcationReport = classification_report(y_pred= t_pred, y_true=t_test)
print(classififcationReport)

[[38  1  0  0  0  0  1  2  1  5]
 [ 0 42  0  0  1  0  0  0  1  0]
 [ 2  0 26  0  4  0  2  7  0  5]
 [ 1  0  0 35  0  0  0  0  0  0]
 [ 0  0  5  0 37  0  1  0  0  2]
 [ 6  0  0  0  2 26  0  4  2  0]
 [ 1  0  0  0  0  0 41  1  0  0]
 [ 0  0  0  0  2  0  0 35  0  0]
 [ 0  0  0  0  0  0  0  0 31  1]
 [ 1  0  0  0  0  0  1  0  0 42]]
